# Data analysis notebook

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(Path().resolve().parent))

from config import RAW_DATA_DIR, PROCESSED_DATA_DIR, STATIONS

In [2]:
import json
import requests

from datetime import datetime, timedelta, timezone
from pprint import pprint

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
milan_lampugnano_df = pd.read_csv(PROCESSED_DATA_DIR / 'milan_lampugnano_departures.csv')
genoa_principe_df = pd.read_csv(PROCESSED_DATA_DIR / 'genoa_principe_departures.csv')

In [4]:
milan_lampugnano_df.head()

,id,bus_code,direction,name,deviation_seconds,updated_at,scheduled_timestamp
0,de537b6e-6804-4d10-9bd6-c8d5da92cbff,519,Zurich Bus Station,Rome - Milan - Zürich,2337.0,2026-05-15T15:11:12Z,2026-05-15T16:05:00Z
1,13ebf787-9a5c-46e8-8903-3d6d0d33f112,544,Pisa (Pietrasantina car park),Pisa/Bologna - Milan MXP ✈ - Turin,0.0,2026-05-15T12:55:56Z,2026-05-15T16:25:00Z
2,e4f7caad-2450-4333-b066-2363c9dd8f6e,480,Turin (Vittorio Emanuele),Bergamo - Lyon/Turin,NaN,NaN,2026-05-15T16:30:00Z
3,ba908a61-bb15-4d14-a434-eec6d8ceb0a7,CIT3197,Milan (Malpensa Airport Terminal 1),Standard,NaN,NaN,2026-05-15T16:30:00Z
4,bc9d4952-78ab-4b1a-bf30-44750e8f1bf1,CIT3197,Milan (Malpensa Airport Terminal 2),Standard,NaN,NaN,2026-05-15T16:30:00Z

In [5]:
genoa_principe_df.head()

,id,bus_code,direction,name,deviation_seconds,updated_at,scheduled_timestamp
0,03222d3c-dcc9-4785-aad0-59e57ba886fe,1501,Florence (Villa Costanza),Florence - Dijon,423.0,2026-05-15T15:13:06Z,2026-05-15T16:20:00Z
1,cbf3475b-7f28-4194-a4e8-f49cae120bda,N718,Bordeaux (Saint-Jean - Paludate),Bordeaux - Nice - Florence,0.0,2026-05-15T15:17:42Z,2026-05-15T16:35:00Z
2,b433d016-a6ac-4568-ac11-01524dbb150e,N1501,Sala Consilina,Sala Consilina - Nice Airport,0.0,2026-05-15T15:09:58Z,2026-05-15T17:10:00Z
3,2a7b581c-470c-4e36-8c2d-aea4147f11c6,1500,Milan (Lampugnano bus station),Milan - Pisa - Naples,0.0,2026-05-15T05:59:44Z,2026-05-15T17:40:00Z
4,e5955048-64b4-4785-8268-6f969fc46062,501,Turin (Vittorio Emanuele),Turin - Naples,0.0,2026-05-15T15:11:10Z,2026-05-15T17:55:00Z